import { Product } from './types';
import { getProductGroups, convertToWooCommerceFormat } from './products';

// Generate mock products from product groups - shows only base products without duration variants
export const mockProducts: Product[] = getProductGroups().map(group => {
  // Use the cheapest variant as the base product for display
  const baseProduct = group.variants[0]; // Already sorted by price
  return convertToWooCommerceFormat(baseProduct);
}) as Product[];

// Legacy mock products for backwards compatibility - now generated from products.json
export const legacyMockProducts: Product[] = [
  // CS2 Products
  {
    id: 1,
    name: 'CS2 Premium Hack',
    slug: 'cs2-premium-hack',
    permalink: '/products/cs2-premium-hack',
    date_created: new Date().toISOString(),
    date_created_gmt: new Date().toISOString(),
    date_modified: new Date().toISOString(),
    date_modified_gmt: new Date().toISOString(),
    type: 'simple',
    status: 'publish',
    featured: true,
    catalog_visibility: 'visible',
    description: 'Premium CS2 hack with aimbot, wallhack, ESP, and anti-cheat bypass. Undetected and safe.',
    short_description: 'Premium undetected CS2 hack with aimbot, wallhack & ESP',
    sku: 'CS2-PREMIUM-001',
    price: '29.99',
    regular_price: '29.99',
    sale_price: '',
    date_on_sale_from: null,
    date_on_sale_from_gmt: null,
    date_on_sale_to: null,
    date_on_sale_to_gmt: null,
    on_sale: false,
    purchasable: true,
    total_sales: 1250,
    virtual: true,
    downloadable: true,
    external_url: '',
    button_text: '',
    tax_status: 'taxable',
    tax_class: '',
    manage_stock: true,
    stock_quantity: 999,
    stock_status: 'instock',
    backorders: 'no',
    backorders_allowed: false,
    backordered: false,
    low_stock_amount: null,
    sold_individually: false,
    weight: '',
    shipping_required: false,
    shipping_taxable: false,
    shipping_class: '',
    shipping_class_id: 0,
    reviews_allowed: true,
    average_rating: '4.8',
    rating_count: 256,
    upsell_ids: [],
    cross_sell_ids: [],
    parent_id: 0,
    purchase_note: '',
    categories: [{ id: 1, name: 'CS2', slug: 'cs2' }],
    tags: [{ id: 1, name: 'Aimbot', slug: 'aimbot' }, { id: 2, name: 'Wallhack', slug: 'wallhack' }],
    images: [
      {
        id: 1,
        date_created: new Date().toISOString(),
        date_created_gmt: new Date().toISOString(),
        date_modified: new Date().toISOString(),
        date_modified_gmt: new Date().toISOString(),
        src: '/images/cs2-premium.jpg',
        name: 'CS2 Premium Hack',
        alt: 'CS2 Premium Hack Screenshot'
      }
    ],
    attributes: [],
    default_attributes: [],
    variations: [],
    grouped_products: [],
    menu_order: 0,
    related_ids: [2, 3],
    meta_data: []
  },
  {
    id: 2,
    name: 'CS2 Aimbot Pro',
    slug: 'cs2-aimbot-pro',
    permalink: '/products/cs2-aimbot-pro',
    date_created: new Date().toISOString(),
    date_created_gmt: new Date().toISOString(),
    date_modified: new Date().toISOString(),
    date_modified_gmt: new Date().toISOString(),
    type: 'simple',
    status: 'publish',
    featured: false,
    catalog_visibility: 'visible',
    description: 'Advanced aimbot for CS2 with customizable settings, smooth aim, and humanized movements.',
    short_description: 'Advanced CS2 aimbot with humanized movements',
    sku: 'CS2-AIMBOT-001',
    price: '19.99',
    regular_price: '24.99',
    sale_price: '19.99',
    date_on_sale_from: null,
    date_on_sale_from_gmt: null,
    date_on_sale_to: null,
    date_on_sale_to_gmt: null,
    on_sale: true,
    purchasable: true,
    total_sales: 890,
    virtual: true,
    downloadable: true,
    external_url: '',
    button_text: '',
    tax_status: 'taxable',
    tax_class: '',
    manage_stock: true,
    stock_quantity: 999,
    stock_status: 'instock',
    backorders: 'no',
    backorders_allowed: false,
    backordered: false,
    low_stock_amount: null,
    sold_individually: false,
    weight: '',
    shipping_required: false,
    shipping_taxable: false,
    shipping_class: '',
    shipping_class_id: 0,
    reviews_allowed: true,
    average_rating: '4.6',
    rating_count: 178,
    upsell_ids: [],
    cross_sell_ids: [],
    parent_id: 0,
    purchase_note: '',
    categories: [{ id: 1, name: 'CS2', slug: 'cs2' }],
    tags: [{ id: 1, name: 'Aimbot', slug: 'aimbot' }],
    images: [
      {
        id: 2,
        date_created: new Date().toISOString(),
        date_created_gmt: new Date().toISOString(),
        date_modified: new Date().toISOString(),
        date_modified_gmt: new Date().toISOString(),
        src: '/images/cs2-aimbot.jpg',
        name: 'CS2 Aimbot Pro',
        alt: 'CS2 Aimbot Pro Interface'
      }
    ],
    attributes: [],
    default_attributes: [],
    variations: [],
    grouped_products: [],
    menu_order: 0,
    related_ids: [1, 3],
    meta_data: []
  },
  {
    id: 3,
    name: 'CS2 ESP & Wallhack',
    slug: 'cs2-esp-wallhack',
    permalink: '/products/cs2-esp-wallhack',
    date_created: new Date().toISOString(),
    date_created_gmt: new Date().toISOString(),
    date_modified: new Date().toISOString(),
    date_modified_gmt: new Date().toISOString(),
    type: 'simple',
    status: 'publish',
    featured: false,
    catalog_visibility: 'visible',
    description: 'See through walls and track enemies with our advanced ESP and wallhack for CS2.',
    short_description: 'Advanced ESP and wallhack for CS2',
    sku: 'CS2-ESP-001',
    price: '15.99',
    regular_price: '15.99',
    sale_price: '',
    date_on_sale_from: null,
    date_on_sale_from_gmt: null,
    date_on_sale_to: null,
    date_on_sale_to_gmt: null,
    on_sale: false,
    purchasable: true,
    total_sales: 567,
    virtual: true,
    downloadable: true,
    external_url: '',
    button_text: '',
    tax_status: 'taxable',
    tax_class: '',
    manage_stock: true,
    stock_quantity: 999,
    stock_status: 'instock',
    backorders: 'no',
    backorders_allowed: false,
    backordered: false,
    low_stock_amount: null,
    sold_individually: false,
    weight: '',
    shipping_required: false,
    shipping_taxable: false,
    shipping_class: '',
    shipping_class_id: 0,
    reviews_allowed: true,
    average_rating: '4.7',
    rating_count: 134,
    upsell_ids: [],
    cross_sell_ids: [],
    parent_id: 0,
    purchase_note: '',
    categories: [{ id: 1, name: 'CS2', slug: 'cs2' }],
    tags: [{ id: 2, name: 'Wallhack', slug: 'wallhack' }, { id: 3, name: 'ESP', slug: 'esp' }],
    images: [
      {
        id: 3,
        date_created: new Date().toISOString(),
        date_created_gmt: new Date().toISOString(),
        date_modified: new Date().toISOString(),
        date_modified_gmt: new Date().toISOString(),
        src: '/images/cs2-esp.jpg',
        name: 'CS2 ESP & Wallhack',
        alt: 'CS2 ESP & Wallhack Screenshot'
      }
    ],
    attributes: [],
    default_attributes: [],
    variations: [],
    grouped_products: [],
    menu_order: 0,
    related_ids: [1, 2],
    meta_data: []
  },
  // BF6 Products
  {
    id: 4,
    name: 'BF6 Ultimate Hack',
    slug: 'bf6-ultimate-hack',
    permalink: '/products/bf6-ultimate-hack',
    date_created: new Date().toISOString(),
    date_created_gmt: new Date().toISOString(),
    date_modified: new Date().toISOString(),
    date_modified_gmt: new Date().toISOString(),
    type: 'simple',
    status: 'publish',
    featured: true,
    catalog_visibility: 'visible',
    description: 'Complete BF6 hack suite with aimbot, ESP, radar, vehicle hacks, and anti-cheat protection.',
    short_description: 'Ultimate BF6 hack with aimbot, ESP & radar',
    sku: 'BF6-ULTIMATE-001',
    price: '34.99',
    regular_price: '34.99',
    sale_price: '',
    date_on_sale_from: null,
    date_on_sale_from_gmt: null,
    date_on_sale_to: null,
    date_on_sale_to_gmt: null,
    on_sale: false,
    purchasable: true,
    total_sales: 2100,
    virtual: true,
    downloadable: true,
    external_url: '',
    button_text: '',
    tax_status: 'taxable',
    tax_class: '',
    manage_stock: true,
    stock_quantity: 999,
    stock_status: 'instock',
    backorders: 'no',
    backorders_allowed: false,
    backordered: false,
    low_stock_amount: null,
    sold_individually: false,
    weight: '',
    shipping_required: false,
    shipping_taxable: false,
    shipping_class: '',
    shipping_class_id: 0,
    reviews_allowed: true,
    average_rating: '4.9',
    rating_count: 342,
    upsell_ids: [],
    cross_sell_ids: [],
    parent_id: 0,
    purchase_note: '',
    categories: [{ id: 2, name: 'BF6', slug: 'bf6' }],
    tags: [{ id: 1, name: 'Aimbot', slug: 'aimbot' }, { id: 4, name: 'Radar', slug: 'radar' }],
    images: [
      {
        id: 4,
        date_created: new Date().toISOString(),
        date_created_gmt: new Date().toISOString(),
        date_modified: new Date().toISOString(),
        date_modified_gmt: new Date().toISOString(),
        src: '/images/bf6-ultimate.jpg',
        name: 'BF6 Ultimate Hack',
        alt: 'BF6 Ultimate Hack Interface'
      }
    ],
    attributes: [],
    default_attributes: [],
    variations: [],
    grouped_products: [],
    menu_order: 0,
    related_ids: [5, 6],
    meta_data: []
  },
  {
    id: 5,
    name: 'BF6 Aimbot & ESP',
    slug: 'bf6-aimbot-esp',
    permalink: '/products/bf6-aimbot-esp',
    date_created: new Date().toISOString(),
    date_created_gmt: new Date().toISOString(),
    date_modified: new Date().toISOString(),
    date_modified_gmt: new Date().toISOString(),
    type: 'simple',
    status: 'publish',
    featured: false,
    catalog_visibility: 'visible',
    description: 'Professional-grade aimbot and ESP for Battlefield 6 with customizable settings.',
    short_description: 'Professional BF6 aimbot and ESP',
    sku: 'BF6-AIM-ESP-001',
    price: '24.99',
    regular_price: '29.99',
    sale_price: '24.99',
    date_on_sale_from: null,
    date_on_sale_from_gmt: null,
    date_on_sale_to: null,
    date_on_sale_to_gmt: null,
    on_sale: true,
    purchasable: true,
    total_sales: 1456,
    virtual: true,
    downloadable: true,
    external_url: '',
    button_text: '',
    tax_status: 'taxable',
    tax_class: '',
    manage_stock: true,
    stock_quantity: 999,
    stock_status: 'instock',
    backorders: 'no',
    backorders_allowed: false,
    backordered: false,
    low_stock_amount: null,
    sold_individually: false,
    weight: '',
    shipping_required: false,
    shipping_taxable: false,
    shipping_class: '',
    shipping_class_id: 0,
    reviews_allowed: true,
    average_rating: '4.5',
    rating_count: 298,
    upsell_ids: [],
    cross_sell_ids: [],
    parent_id: 0,
    purchase_note: '',
    categories: [{ id: 2, name: 'BF6', slug: 'bf6' }],
    tags: [{ id: 1, name: 'Aimbot', slug: 'aimbot' }, { id: 3, name: 'ESP', slug: 'esp' }],
    images: [
      {
        id: 5,
        date_created: new Date().toISOString(),
        date_created_gmt: new Date().toISOString(),
        date_modified: new Date().toISOString(),
        date_modified_gmt: new Date().toISOString(),
        src: '/images/bf6-aimbot.jpg',
        name: 'BF6 Aimbot & ESP',
        alt: 'BF6 Aimbot & ESP Screenshot'
      }
    ],
    attributes: [],
    default_attributes: [],
    variations: [],
    grouped_products: [],
    menu_order: 0,
    related_ids: [4, 6],
    meta_data: []
  },
  {
    id: 6,
    name: 'BF6 Radar Hack',
    slug: 'bf6-radar-hack',
    permalink: '/products/bf6-radar-hack',
    date_created: new Date().toISOString(),
    date_created_gmt: new Date().toISOString(),
    date_modified: new Date().toISOString(),
    date_modified_gmt: new Date().toISOString(),
    type: 'simple',
    status: 'publish',
    featured: false,
    catalog_visibility: 'visible',
    description: 'Advanced radar system for BF6 showing enemy positions, vehicles, and objectives.',
    short_description: 'Advanced BF6 radar system',
    sku: 'BF6-RADAR-001',
    price: '18.99',
    regular_price: '18.99',
    sale_price: '',
    date_on_sale_from: null,
    date_on_sale_from_gmt: null,
    date_on_sale_to: null,
    date_on_sale_to_gmt: null,
    on_sale: false,
    purchasable: true,
    total_sales: 789,
    virtual: true,
    downloadable: true,
    external_url: '',
    button_text: '',
    tax_status: 'taxable',
    tax_class: '',
    manage_stock: true,
    stock_quantity: 999,
    stock_status: 'instock',
    backorders: 'no',
    backorders_allowed: false,
    backordered: false,
    low_stock_amount: null,
    sold_individually: false,
    weight: '',
    shipping_required: false,
    shipping_taxable: false,
    shipping_class: '',
    shipping_class_id: 0,
    reviews_allowed: true,
    average_rating: '4.4',
    rating_count: 156,
    upsell_ids: [],
    cross_sell_ids: [],
    parent_id: 0,
    purchase_note: '',
    categories: [{ id: 2, name: 'BF6', slug: 'bf6' }],
    tags: [{ id: 4, name: 'Radar', slug: 'radar' }],
    images: [
      {
        id: 6,
        date_created: new Date().toISOString(),
        date_created_gmt: new Date().toISOString(),
        date_modified: new Date().toISOString(),
        date_modified_gmt: new Date().toISOString(),
        src: '/images/bf6-radar.jpg',
        name: 'BF6 Radar Hack',
        alt: 'BF6 Radar Hack Interface'
      }
    ],
    attributes: [],
    default_attributes: [],
    variations: [],
    grouped_products: [],
    menu_order: 0,
    related_ids: [4, 5],
    meta_data: []
  }
];

// Filter functions for different categories
export const getCS2Products = (): Product[] => {
  return mockProducts.filter(product => 
    product.categories.some(category => category.slug === 'cs2')
  );
};

export const getBF6Products = (): Product[] => {
  return mockProducts.filter(product => 
    product.categories.some(category => category.slug === 'bf6')
  );
};

export const getFeaturedProducts = (): Product[] => {
  return mockProducts.filter(product => product.featured);
};